blog_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
    path('blog/', include('blogapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

blogapp/urls.py
from django.urls import path

from blogapp import views


urlpatterns = [
    path('', views.index, name='index'),
    path('blogs/', views.BlogsListView.as_view(), name='blogs'),
    path('<int:pk>', views.BlogDetailView.as_view(), name='blog'),
    path('blogger/<int:pk>', views.BloggerDetailView.as_view(), name='blogger'),
    path('bloggers/', views.BloggersListView.as_view(), name='bloggers'),
    path('blog/<int:blog_id>/create', views.CommentCreateView.as_view(), name='comment_create'),
]

blogapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Blog(models.Model):

    class Meta:
        ordering = ['pk']

    post_date = models.DateTimeField(auto_now=True)
    title = models.TextField()
    content = models.TextField()
    author = models.ForeignKey('Blogger', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.pk} {self.title}'

    def get_absolute_url(self):
        return reverse('blog', args=[self.pk])


class Blogger(models.Model):

    class Meta:
        ordering = ['pk']

    name = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField()

    def __str__(self):
        return f'{self.pk} {self.name}'

    def get_absolute_url(self):
        return reverse('blogger', args=[self.pk])


class Comment(models.Model):

    post_date = models.DateTimeField(auto_now=True)
    comment = models.TextField()
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.pk} {self.comment[:15]}'

blogapp/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin as LR
from django.shortcuts import get_object_or_404, render

from blogapp import models


def index(request):
    return render(request, 'index.html')


class BlogsListView(ListView):

    model = models.Blog
    template_name = 'blogapp/blogs_list.html'
    paginate_by = 5


class BlogDetailView(DetailView):

    model = models.Blog
    template_name = 'blogapp/blog_detail.html'


class BloggerDetailView(DetailView):

    model = models.Blogger
    template_name = 'blogapp/blogger_detail.html'


class BloggersListView(ListView):

    model = models.Blogger
    template_name = 'blogapp/bloggers_list.html'
    paginate_by = 5


class CommentCreateView(LR, CreateView):

    model = models.Comment
    fields = ['comment']
    template_name = 'blogapp/comment_create.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['blog'] = get_object_or_404(
            models.Blog, pk=self.kwargs['blog_id'])
        return data

    def form_valid(self, form):
        form.instance.blog = get_object_or_404(
            models.Blog, pk=self.kwargs['blog_id'])
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return self.object.blog.get_absolute_url()

blogapp/templates/blogapp/blog_detail.html
{% extends 'base_generic.html' %}

{% block content %}

  <h1>{{ object.title }}</h1>
  <p><strong>Post date</strong> {{ object.post_date }}</p>
  <p><strong>Author:</strong> <a href="{% url 'blogger' object.author.pk %}">{{ object.author.name }}</a></p>
  <p><strong>Description:</strong></p>
  <p style="white-space:pre-wrap;">{{ object.content }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Comments</h4>
    {% for comment in object.comment_set.all %}
      <p> {{ comment.comment }} ({{ comment.user }} - {{ comment.post_date }})</p>
    {% endfor %}

    <a href="{% url 'comment_create' object.pk %}">create comment</a>

  </div>

{% endblock %}

blogapp/templates/blogapp/blogger_detail.html
{% extends 'base_generic.html' %}

{% block content %}

  <h1>{{ object.name }}</h1>
  <p style="white-space:pre-wrap;">{{ object.bio }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Blog Post</h4>
    {% for blog in object.blog_set.all %}
      <p><a href="{{ blog.get_absolute_url }}"> {{ blog.title }}</a> ({{ blog.post_date }})</p>
    {% endfor %}
  </div>

{% endblock %}

blogapp/templates/blogapp/bloggers_list.html
{% extends 'base_generic.html' %}

{% block content %}

  <table class="table">
    <thead>
      <tr>
        <th scope="col">name</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
        <tr>
          <td><a href="{{ object.get_absolute_url }}">{{ object.name }}</a></td>
        </tr>
      {% endfor %}
    </tbody>
  <table>

{% endblock %}

blogapp/templates/blogapp/blogs_list.html
{% extends 'base_generic.html' %}

{% block content %}

  <table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Post Date</th>
        <th scope="col">Title</th>
        <th scope="col">Author</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
        <tr>
          <td>{{object.id}}</td>
          <td><a href="{{ object.get_absolute_url }}">{{ object.post_date }}</a></td>
          <td>{{ object.title }}</td>
          <td>{{ object.author.name }}</td>
        </tr>
      {% endfor %}
    </tbody>
  <table>

{% endblock %}

blogapp/templates/blogapp/comment_create.html
{% extends 'base_generic.html' %}
su
{% block content %}
  <p> create comment for {{blog.title }} </p>
  <form method="POST" action="{% url 'comment_create' blog.pk %}">
    {% csrf_token %}
    <div class="form-group">
      {{ form.comment.label_tag }}
      {{ form.comment }}
    </div>
    <input type="submit" class="btn btn-link", value="Add">
  </div>
{% endblock %}

templates/base_generic.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="author" content="Anry">
    <meta name="description" content="Dev Blog">
    <meta name="keywords" content="django,blog,beginner">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <script defer src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script defer src="{% static 'js/bootstrap.min.js' %}"></script>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'blogs' %}">blogs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'bloggers' %}">bloggers</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'logout' %}?next={{request.path}}">{{ user.get_username }} logout</a>
            {% else %}
              <a class="nav-link" href="{% url 'login' %}?next={{request.path}}">login</a>
            {% endif %}
          </li>
        </ul>

      </div>
    </nav>

    <div class="container-fluid">

      {% block content %}
      {% endblock %}

      {% if is_paginated %}
        <nav aria-label="Page Navigation">
          <ul class="pagination pagination-sm justify-content-center">
            {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a>
              </li>
            {% endif %}
              <li class="page-item" aria-current="page">
                <span class="page-link">
                  Page {{ page_obj.number }} of {{ paginator.num_pages }}
                  <span class="sr-only">(current)</span>
                </span>
              </li>
            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
              </li>
            {% endif %}
          </ul>
        </nav>
      {% endif %}

    </div>
  </body>
</html>

templates/index.html
{% extends "base_generic.html" %}